### ISSUE TITLE
Failed in Run inpainting (ValueError: torch.cuda.is_available() should be True but is False. xformers' memory efficient attention is only available for GPU)

### ISSUE THREAD

**Issue by RoychenHKMU** [Uminosachi/inpaint-anything#19]
CPU: i9 13900k
GPU:4090
I follow the GitHub tutorial, but in the last step "Run inpainting" after a few min loading, it show error message. please someone help thank you so much.

error message below.

Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
input_image: (4000, 6000, 3) uint8
SamAutomaticMaskGenerator sam_vit_b_01ec64.pth
SAM processing time: 124.52666926383972
Uminosachi/dreamshaper_6Inpainting
Downloading (…)ain/model_index.json: 100%|█████████████████████████████████████████████████████████| 579/579 [00:00<00:00, 1.15MB/s]
text_encoder\model.safetensors not found
Downloading (…)cheduler_config.json: 100%|█████████████████████████████████████████████████████████████████| 460/460 [00:00<?, ?B/s]
Downloading (…)rocessor_config.json: 100%|█████████████████████████████████████████████████████████████████| 520/520 [00:00<?, ?B/s]
Downloading (…)_checker/config.json: 100%|█████████████████████████████████████████████████████| 4.58k/4.58k [00:00<00:00, 4.59MB/s]
Downloading (…)_encoder/config.json: 100%|█████████████████████████████████████████████████████████████████| 612/612 [00:00<?, ?B/s]
Downloading (…)cial_tokens_map.json: 100%|█████████████████████████████████████████████████████████████████| 472/472 [00:00<?, ?B/s]
Downloading (…)okenizer_config.json: 100%|█████████████████████████████████████████████████████████| 737/737 [00:00<00:00, 1.47MB/s]
Downloading (…)6c9/unet/config.json: 100%|█████████████████████████████████████████████████████| 1.55k/1.55k [00:00<00:00, 2.60MB/s]
Downloading (…)tokenizer/merges.txt: 100%|████████████████████████████████████████████████████████| 525k/525k [00:00<00:00, 931kB/s]
Downloading (…)e6c9/vae/config.json: 100%|█████████████████████████████████████████████████████████████████| 577/577 [00:00<?, ?B/s]
Downloading (…)tokenizer/vocab.json: 100%|█████████████████████████████████████████████████████| 1.06M/1.06M [00:00<00:00, 1.34MB/s]
Downloading pytorch_model.bin: 100%|█████████████████████████████████████████████████████████████| 246M/246M [00:20<00:00, 11.9MB/s]
Downloading (…)on_pytorch_model.bin: 100%|███████████████████████████████████████████████████████| 167M/167M [00:29<00:00, 5.67MB/s]
Downloading pytorch_model.bin: 100%|█████████████████████████████████████████████████████████████| 608M/608M [00:46<00:00, 13.1MB/s]
Downloading (…)on_pytorch_model.bin: 100%|█████████████████████████████████████████████████████| 1.72G/1.72G [01:55<00:00, 14.9MB/s]
Fetching 15 files: 100%|████████████████████████████████████████████████████████████████████████████| 15/15 [01:57<00:00,  7.83s/it]
C:\Users\user\anaconda3\envs\inpaint\lib\site-packages\transformers\models\clip\feature_extraction_clip.py:28: FutureWarning: The class CLIPFeatureExtractor is deprecated and will be removed in version 5 of Transformers. Please use CLIPImageProcessor instead.7MB/s]
  warnings.warn(n_pytorch_model.bin: 100%|█████████████████████████████████████████████████████| 1.72G/1.72G [01:55<00:00, 21.3MB/s]
The config attributes {'addition_embed_type': None, 'addition_embed_type_num_heads': 64, 'class_embeddings_concat': False, 'cross_attention_norm': None, 'encoder_hid_dim': None, 'mid_block_only_cross_attention': None, 'resnet_out_scale_factor': 1.0, 'resnet_skip_time_act': False, 'time_embedding_act_fn': None, 'time_embedding_dim': None} were passed to UNet2DConditionModel, but are not expected and will be ignored. Please verify your config.json configuration file.
Using sampler DDIM
Traceback (most recent call last):
  File "C:\Users\user\anaconda3\envs\inpaint\lib\site-packages\gradio\routes.py", line 427, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\user\anaconda3\envs\inpaint\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "C:\Users\user\anaconda3\envs\inpaint\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\user\anaconda3\envs\inpaint\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\user\anaconda3\envs\inpaint\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\user\anaconda3\envs\inpaint\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Researchteam\Inpainting anything\inpaint-anything\iasam_app.py", line 465, in run_inpaint
    pipe.enable_xformers_memory_efficient_attention()
  File "C:\Users\user\anaconda3\envs\inpaint\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 1080, in enable_xformers_memory_efficient_attention
    self.set_use_memory_efficient_attention_xformers(True, attention_op)
  File "C:\Users\user\anaconda3\envs\inpaint\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 1105, in set_use_memory_efficient_attention_xformers
    fn_recursive_set_mem_eff(module)
  File "C:\Users\user\anaconda3\envs\inpaint\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 1096, in fn_recursive_set_mem_eff
    module.set_use_memory_efficient_attention_xformers(valid, attention_op)
  File "C:\Users\user\anaconda3\envs\inpaint\lib\site-packages\diffusers\models\modeling_utils.py", line 219, in set_use_memory_efficient_attention_xformers
    fn_recursive_set_mem_eff(module)
  File "C:\Users\user\anaconda3\envs\inpaint\lib\site-packages\diffusers\models\modeling_utils.py", line 215, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "C:\Users\user\anaconda3\envs\inpaint\lib\site-packages\diffusers\models\modeling_utils.py", line 215, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "C:\Users\user\anaconda3\envs\inpaint\lib\site-packages\diffusers\models\modeling_utils.py", line 215, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "C:\Users\user\anaconda3\envs\inpaint\lib\site-packages\diffusers\models\modeling_utils.py", line 212, in fn_recursive_set_mem_eff
    module.set_use_memory_efficient_attention_xformers(valid, attention_op)
  File "C:\Users\user\anaconda3\envs\inpaint\lib\site-packages\diffusers\models\attention.py", line 104, in set_use_memory_efficient_attention_xformers
    raise ValueError(
ValueError: torch.cuda.is_available() should be True but is False. xformers' memory efficient attention is only available for GPU

**Comment by Uminosachi** [comment]
Could you please confirm whether [CUDA](https://developer.nvidia.com/cuda-toolkit-archive) and [cuDNN](https://developer.nvidia.com/cudnn) have been installed?

**Comment by Uminosachi** [comment]
If CUDA is installed on your system, you can install the torch package for CUDA using the command below.

```
pip install -r requirements_cu118.txt
```

**Comment by RoychenHKMU** [comment]
> If CUDA is installed on your system, you can install the torch package for CUDA using the command below.
> 
> ```
> pip install -r requirements_cu118.txt
> ```

Thank you so much for reply and help, I installed CUDA 12.1 and the CUDA toolkit set, also install the cuDNN (cudnn-windows-x86_64-8.9.2.26_cuda12-archive), then i run the command (pip install -r requirements_cu118.txt). 

After that i lunch the UI by using (python iasam_app.py) it show a warning message, i think this is not a necessary problem right?

 "WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.0.1+cu118 with CUDA 1108 (you have 2.0.1+cpu)
    Python  3.10.11 (you have 3.10.11)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
platform: Windows"

After that, I try to use inpainting, it show the same error message as before, but the "Cleaner" and "Mask only" function work fine.
"ValueError: torch.cuda.is_available() should be True but is False. xformers' memory efficient attention is only available for GPU"

**Comment by Uminosachi** [comment]
Could you add the `--force-reinstall` option when you run pip install? It seems that the CPU version of torch is still present.

```
pip install --force-reinstall -r requirements_cu118.txt
```
